// Year,Bene_Geo_Lvl,Bene_Geo_Desc,Bene_Geo_Cd,Bene_Age_Lvl,Benes_Wth_PTAPTB_Cnt,Benes_FFS_Cnt,Benes_MA_Cnt,
// MA_Prtcptn_Rate,Bene_Avg_Age,Bene_Feml_Pct,Bene_Male_Pct,Bene_Race_Wht_Pct,Bene_Race_Black_Pct,Bene_Race_Hspnc_Pct,
// Bene_Race_Othr_Pct,Bene_Dual_Pct,Bene_Avg_Risk_Scre,Tot_Mdcr_Pymt_Amt,Tot_Mdcr_Stdzd_Pymt_Amt,Tot_Mdcr_Stdzd_RA_Pymt_Amt,
// Tot_Mdcr_Pymt_PC,Tot_Mdcr_Stdzd_Pymt_PC,Tot_Mdcr_Stdzd_RA_Pymt_PC,IP_Mdcr_Pymt_Amt,IP_Mdcr_Pymt_Pct,IP_Mdcr_Pymt_PC,
// IP_Mdcr_Pymt_Per_User,IP_Mdcr_Stdzd_Pymt_Amt,IP_Mdcr_Stdzd_Pymt_Pct,IP_Mdcr_Stdzd_Pymt_PC,IP_Mdcr_Stdzd_Pymt_Per_User,
// Benes_IP_Cvrd_Stay_Cnt,Benes_IP_Pct,IP_Cvrd_Stays_Per_1000_Benes,IP_Cvrd_Days_Per_1000_Benes,Acute_Hosp_Readmsn_Cnt,
// Acute_Hosp_Readmsn_Pct,Benes_ER_Visits_Cnt,ER_Visits_Per_1000_Benes,Benes_ER_Visits_Pct,OP_Mdcr_Pymt_Amt,OP_Mdcr_Pymt_Pct,
// OP_Mdcr_Pymt_PC,OP_Mdcr_Pymt_Per_User,OP_Mdcr_Stdzd_Pymt_Amt,OP_Mdcr_Stdzd_Pymt_Pct,OP_Mdcr_Stdzd_Pymt_PC,OP_Mdcr_Stdzd_Pymt_Per_User,
// Benes_OP_Cnt,Benes_OP_Pct,OP_Visits_Per_1000_Benes,ASC_Mdcr_Pymt_Amt,ASC_Mdcr_Pymt_Pct,ASC_Mdcr_Pymt_PC,ASC_Mdcr_Pymt_Per_User,
// ASC_Mdcr_Stdzd_Pymt_Amt,ASC_Mdcr_Stdzd_Pymt_Pct,ASC_Mdcr_Stdzd_Pymt_PC,ASC_Mdcr_Stdzd_Pymt_Per_User,
// Benes_ASC_Cnt,Benes_ASC_Pct,ASC_Events_Per_1000_Benes,SNF_Mdcr_Pymt_Amt,SNF_Mdcr_Pymt_Pct,SNF_Mdcr_Pymt_PC,SNF_Mdcr_Pymt_Per_User,
// SNF_Mdcr_Stdzd_Pymt_Amt,SNF_Mdcr_Stdzd_Pymt_Pct,SNF_Mdcr_Stdzd_Pymt_PC,SNF_Mdcr_Stdzd_Pymt_Per_User,Benes_SNF_Cnt,Benes_SNF_Pct,
// SNF_Cvrd_Stays_Per_1000_Benes,SNF_Cvrd_Days_Per_1000_Benes,IRF_Mdcr_Pymt_Amt,IRF_Mdcr_Pymt_Pct,IRF_Mdcr_Pymt_PC,IRF_Mdcr_Pymt_Per_User,
// IRF_Mdcr_Stdzd_Pymt_Amt,IRF_Mdcr_Stdzd_Pymt_Pct,IRF_Mdcr_Stdzd_Pymt_PC,IRF_Mdcr_Stdzd_Pymt_Per_User,Benes_IRF_Cnt,Benes_IRF_Pct,
// IRF_Cvrd_Stays_Per_1000_Benes,IRF_Cvrd_Days_Per_1000_Benes,LTCH_Mdcr_Pymt_Amt,LTCH_Mdcr_Pymt_Pct,LTCH_Mdcr_Pymt_PC,LTCH_Mdcr_Pymt_Per_User,
// LTCH_Mdcr_Stdzd_Pymt_Amt,LTCH_Mdcr_Stdzd_Pymt_Pct,LTCH_Mdcr_Stdzd_Pymt_PC,LTCH_Mdcr_Stdzd_Pymt_Per_User,Benes_LTCH_Cnt,Benes_LTCH_Pct,
// LTCH_Cvrd_Stays_Per_1000_Benes,LTCH_Cvrd_Days_Per_1000_Benes,HH_Mdcr_Pymt_Amt,HH_Mdcr_Pymt_Pct,HH_Mdcr_Pymt_PC,HH_Mdcr_Pymt_Per_User,
// HH_Mdcr_Stdzd_Pymt_Amt,HH_Mdcr_Stdzd_Pymt_Pct,HH_Mdcr_Stdzd_Pymt_PC,HH_Mdcr_Stdzd_Pymt_Per_User,Benes_HH_Cnt,Benes_HH_Pct,
// HH_Cvrd_Stays_Per_1000_Benes,HH_Visits_Per_1000_Benes,Hospc_Mdcr_Pymt_Amt,Hospc_Mdcr_Pymt_Pct,Hospc_Mdcr_Pymt_PC,
// Hospc_Mdcr_Pymt_Per_User,Hospc_Mdcr_Stdzd_Pymt_Amt,Hospc_Mdcr_Stdzd_Pymt_Pct,Hospc_Mdcr_Stdzd_Pymt_PC,Hospc_Mdcr_Stdzd_Pymt_Per_User,
// Benes_Hospc_Cnt,Benes_Hospc_Pct,Hospc_Cvrd_Stays_Per_1000_Benes,Hospc_Cvrd_Days_Per_1000_Benes,EM_Mdcr_Pymt_Amt,EM_Mdcr_Pymt_Pct,EM_Mdcr_Pymt_PC,
// EM_Mdcr_Pymt_Per_User,EM_Mdcr_Stdzd_Pymt_Amt,EM_Mdcr_Stdzd_Pymt_Pct,EM_Mdcr_Stdzd_Pymt_PC,EM_Mdcr_Stdzd_Pymt_Per_User,Benes_EM_Cnt,Benes_EM_Pct,
// EM_Evnts_Per_1000_Benes,Prcdrs_Mdcr_Pymt_Amt,Prcdrs_Mdcr_Pymt_Pct,Prcdrs_Mdcr_Pymt_PC,Prcdrs_Mdcr_Pymt_Per_User,Prcdrs_Mdcr_Stdzd_Pymt_Amt,
// Prcdrs_Mdcr_Stdzd_Pymt_Pct,Prcdrs_Mdcr_Stdzd_Pymt_PC,Prcdrs_Mdcr_Stdzd_Pymt_Per_User,Benes_Prcdrs_Cnt,Benes_Prcdrs_Pct,Prcdr_Evnts_Per_1000_Benes,
// Tests_Mdcr_Pymt_Amt,Tests_Mdcr_Pymt_Pct,Tests_Mdcr_Pymt_PC,Tests_Mdcr_Pymt_Per_User,Tests_Mdcr_Stdzd_Pymt_Amt,Tests_Mdcr_Stdzd_Pymt_Pct,
// Tests_Mdcr_Stdzd_Pymt_PC,Tests_Mdcr_Stdzd_Pymt_Per_User,Benes_Tests_Cnt,Benes_Test_Pct,Test_Evnts_Per_1000_Benes,Imgng_Mdcr_Pymt_Amt,
// Imgng_Mdcr_Pymt_Pct,Imgng_Mdcr_Pymt_PC,Imgng_Mdcr_Pymt_Per_User,Imgng_Mdcr_Stdzd_Pymt_Amt,Imgng_Mdcr_Stdzd_Pymt_Pct,Imgng_Mdcr_Stdzd_Pymt_PC,
// Imgng_Mdcr_Stdzd_Pymt_Per_User,Benes_Imgng_Cnt,Benes_Imgng_Pct,Imgng_Evnts_Per_1000_Benes,DME_Mdcr_Pymt_Amt,DME_Mdcr_Pymt_Pct,DME_Mdcr_Pymt_PC,
// DME_Mdcr_Pymt_Per_User,DME_Mdcr_Stdzd_Pymt_Amt,DME_Mdcr_Stdzd_Pymt_Pct,DME_Mdcr_Stdzd_Pymt_PC,DME_Mdcr_Stdzd_Pymt_Per_User,Benes_DME_Cnt,Benes_DME_Pct,
// DME_Evnts_Per_1000_Benes,OP_Dlys_Mdcr_Pymt_Amt,OP_Dlys_Mdcr_Pymt_Pct,OP_Dlys_Mdcr_Pymt_PC,OP_Dlys_Mdcr_Pymt_Per_User,OP_Dlys_Mdcr_Stdzd_Pymt_Amt,
// OP_Dlys_Mdcr_Stdzd_Pymt_Pct,OP_Dlys_Mdcr_Stdzd_Pymt_PC,OP_Dlys_Mdcr_Stdzd_Pymt_Per_User,Benes_OP_Dlys_Cnt,Benes_OP_Dlys_Pct,OP_Dlys_Evnts_Per_1000_Benes,
// FQHC_RHC_Mdcr_Pymt_Amt,FQHC_RHC_Mdcr_Pymt_Pct,FQHC_RHC_Mdcr_Pymt_PC,FQHC_RHC_Mdcr_Pymt_Per_User,FQHC_RHC_Mdcr_Stdzd_Pymt_Amt,FQHC_RHC_Mdcr_Stdzd_Pymt_Pct,
// FQHC_RHC_Mdcr_Stdzd_Pymt_PC,FQHC_RHC_Mdcr_Stdzd_Pymt_PU,Benes_FQHC_RHC_Cnt,Benes_FQHC_RHC_Pct,FQHC_RHC_Visits_Per_1000_Benes,Amblnc_Mdcr_Pymt_Amt,
// Amblnc_Mdcr_Pymt_Pct,Amblnc_Mdcr_Pymt_PC,Amblnc_Mdcr_Pymt_Per_User,Amblnc_Mdcr_Stdzd_Pymt_Amt,Amblnc_Mdcr_Stdzd_Pymt_Pct,Amblnc_Mdcr_Stdzd_Pymt_PC,
// Amblnc_Mdcr_Stdzd_Pymt_Per_User,Benes_Amblnc_Cnt,Benes_Amblnc_Pct,Amblnc_Evnts_Per_1000_Benes,PTB_Drugs_Mdcr_Pymt_Amt,PTB_Drugs_Mdcr_Pymt_Pct,
// PTB_Drugs_Mdcr_Pymt_PC,PTB_Drugs_Mdcr_Pymt_PU,PTB_Drugs_Mdcr_Stdzd_Pymt_Amt,PTB_Drugs_Mdcr_Stdzd_Pymt_Pct,PTB_Drugs_Mdcr_Stdzd_Pymt_PC,
// PTB_Drugs_Mdcr_Stdzd_Pymt_PU,Benes_PTB_Drugs_Cnt,Benes_PTB_Drugs_Pct,PTB_Othr_Srvcs_Mdcr_Pymt_Amt,PTB_Othr_Srvcs_Mdcr_Stdzd_Pymt,Tot_PBPMT_Rdctn_Amt,Tot_PBPMT_Rdctn_PCC,
// PQI03_Dbts_Age_LT_65,PQI03_Dbts_Age_65_74,PQI03_Dbts_Age_GE_75,PQI05_COPD_Asthma_Age_40_64,PQI05_COPD_Asthma_Age_65_74,PQI05_COPD_Asthma_Age_GE_75,PQI07_Hyprtnsn_Age_LT_65,
// PQI07_Hyprtnsn_Age_65_74,PQI07_Hyprtnsn_Age_GE_75,PQI08_CHF_Age_LT_65,PQI08_CHF_Age_65_74,PQI08_CHF_Age_GE_75,PQI10_Dhydrtn_Age_LT_65,PQI10_Dhydrtn_Age_65_74,
// PQI10_Dhydrtn_Age_GE_75,PQI11_Bctrl_Pna_Age_LT_65,PQI11_Bctrl_Pna_Age_65_74,PQI11_Bctrl_Pna_Age_GE_75,PQI12_UTI_Age_LT_65,PQI12_UTI_Age_65_74,PQI12_UTI_Age_GE_75,
// PQI15_Asthma_Age_LT_40,PQI16_LwrXtrmty_Amputn_Age_LT_65,PQI16_LwrXtrmty_Amputn_Age_65_74,PQI16_LwrXtrmty_Amputn_Age_GE_75

class MedicareGeoVariation {

  int? year;
  String? graphic_level;
  String? geo_description;
  int? geo_cd;
  String? age;

}